version: "3.9"
services:

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: .
    image: app:latest
    restart: always
    environment:
      spring_datasource_url: jdbc:postgresql://postgres:5432/postgres
    ports:
      - "8080:8080"
    volumes:
      - ./liquibase:/app/liquibase
    depends_on:
      - postgres
